### ISSUE TITLE
Debian packaging

### ISSUE THREAD

**Issue by samcday** [samcday/phrog#10]

**Comment by samcday** [comment]
Okay so I've been staring at various Debian dox and I still feel totally lost.

I'm pretty sure I want gbp, because that's what lets me manage `debian/` in the upstream repo.

I'm pretty sure I want to vendor some crates. At the very least libphosh-rs because of the unreleased changes (and the fact that libphosh-rs is not packaged in Debian yet). But apparently also gtkrs3 stuff and maybe libhandy-rs as well. Still trying to confirm that.

I don't know how to actually "quickstart" a tarball or source directory of :frog:  into a reasonable `debian/`. `dh-build` seems too far away from a Cargo project, but maybe I'm overthinking it. I think I need `debcargo`? But it seems that expects the crate is on crates.io.

I'm gonna put this down for a bit.

**Comment by agx** [comment]
Just to avoid duplication: See https://salsa.debian.org/DebianOnMobile-team/phrog/-/merge_requests/1#note_528652

**Comment by samcday** [comment]
I'm gonna close this out now, as Arnaud has done a whole bunch of amazing work to get phrog packaged in Debian (see the MR Guido linked). I rejiggered some Cargo deps last night to try to accommodate the crate dependency hellscape that stretches over Debian and Fedora.

I still need to figure out if there's a way to completely change a Cargo dependency based on features. That is, when `--features=static` is enabled, I would like to use the local libphosh-rs subtree (which includes the patches to build the local phosh subtree and statically link it), but otherwise consume the proper libphosh+sys crates from crates.io. For now, Debian (and maybe Fedora?) will need to patch this dep.
