### ISSUE TITLE
Use mobi.phosh.phrog namespace?

### ISSUE THREAD

**Issue by agx** [samcday/phrog#26]
Before phrog makes it into distributions: Would it make sense to move places that use reverse DNS notation (like gsettings schema files) to `mobi.phosh.phrog` ? That would put it more in line with other components. Changing later is difficult if one doesn't want to break user settings.

**Comment by samcday** [comment]
:frog: would be honored to be counted amongst the greats :relaxed: Thanks for bringing this up now and sparing me from that migration hassle later
