### ISSUE TITLE
Fade in on session start

### ISSUE THREAD

**Issue by samcday** [samcday/phrog#31]
I think Phosh already does this? Or maybe I saw it in phog. Either way, I wants it.

:frog: should hold the initial paint until lockscreen setup is done (user+session list loaded and widgets are populated, etc) and then do a nice fade-in.

**Comment by agx** [comment]
Phosh notifies 'up' via  a Wayland protocol to phoc which then fades out the shield (if `phoc` is run with `-S`)

**Comment by samcday** [comment]
That's very helpful, thanks. I'm also glad to know what `-S` does now... I'd been wondering why phoc would care that its spawning bash or zsh 😅

**Comment by samcday** [comment]
I pulled some other commits into #32 ... but really all that was necessary was to add `-S` to the nested phoc launch in 28fe55ca8b8de574fe59a824babe347d6731bd80. The shell fades in nicely on startup now:

https://github.com/user-attachments/assets/5c33a1b4-6d0b-4c3d-9217-af46f46f4fdd

I'll need to keep an eye on this, especially when landing changes for #22, where I plan to push fdo Accounts dbus interactions into an async Future. I hope that proves to be straightforward to work around though: I think I can just block the constructor on an init channel that is signalled once the initial data has been loaded from dbus.

**Comment by samcday** [comment]
Hmm, one bummer is that it seems enabling the `-S` option has caused the virtual mouse display to break. Earlier CI recordings showed the mouse moving around on screen. I've also observed this behaviour locally (and actually I've never been able to get the mouse to display correctly locally).

@agx if you have any tips on where I could start my investigation that would be great, at this point I have exactly zero leads :thinking:

**Comment by samcday** [comment]
Sorry, disregard that last message. Looks like it's something else that broke the virtual pointer display.

This is what I deserve for not practicing good PR/commit hygiene :see_no_evil:

**Comment by samcday** [comment]
The issue was actually that I'd changed the tests to *always* spawn phoc. So I finally got around to adding some code to run a quick'n'dirty roundtrip on the compositor to check for the phosh_private interface, and only run a nested phoc if necessary.
