### ISSUE TITLE
Release v0.42.0 when Phosh does

### ISSUE THREAD

**Issue by samcday** [samcday/phrog#44]
Since 99% of this project is Phosh code, it makes sense to follow the upstream versioning and release strategy.

So, when Phosh [releases 0.42 at the end of this month (September '24)](https://gitlab.gnome.org/World/Phosh/phosh/-/wikis/Releases), we should also release :frog: 0.42.0 not long after.

The 0.42.0 release should have Phosh `0.42.0` merged into the `phosh/` subtree. Whatever the latest compatible release of `libphosh-rs` is at that time should also be merged into the `libphosh-rs/` subtree ([I'd like if that was doing lockstep versioning, too](https://gitlab.gnome.org/guidog/libphosh-rs/-/issues/2))

For as long as static/vendored libphosh+libphosh-rs exist in this repository, effort should be maintained to keep the versioning/releasing of :frog: in lockstep with upstream Phosh.

[When libphosh provides longer-term ABI compatibility guarantees](https://gitlab.com/mobian1/phog/-/issues/5#note_2094521769), we can consider adopting a different release/versioning strategy.

**Comment by samcday** [comment]
I'll also release a v0.41.0 later this month. It'll be intended as the most mature build that can make use of the already released libphosh-0.41 artifact. That'll serve as the best starting point for grinding :frog: thru distro packaging processes, I reckon.

**Comment by samcday** [comment]
Didn't manage to cut the first lock-step release in time before Satisfactory 1.0 dropped. I was kinda hoping that fact would only guarantee a couple of weeks of my life was blackholed, but it ended up being more like 5 weeks. A.D.A is happy though, as I've waved her off from our Local Group a couple of times already.

Uh, anyway, I'm gonna cut a 0.42 release now. GNOME Gitlab is down at present so I can't check when the upcoming Phosh milestones are, but I'm assuming they're still every 6 weeks at current.

**Comment by agx** [comment]
yup,  0.43 is mid november.
