### ISSUE TITLE
Fix CI for latest Phosh commits

### ISSUE THREAD

**Issue by samcday** [samcday/phrog#54]
Phosh commit 665d79dd5bd29666908054032626083f7b23ba7a has broken the build over here, because `gsettings-desktop-schemas >= 43`  is not available in Ubuntu package repos.

Getting to the point where Phosh 0.42 could build cleanly in Github Actions environment was tedious and time-consuming last time around. Looks like this is going to be an endless uphill struggle that I'm rapidly losing interest in.

I think maybe a better approach would be to mirror Phosh's Gitlab CI image over here and figure out how to use that during the GHA workflow instead.

**Comment by agx** [comment]
Ubuntu will be too often too old, Debian testing should be sufficient most of the time (we sometimes need to pick some packages from experimental/unstable during the Debian freeze).

**Comment by samcday** [comment]
I was trying to stick to the default runner image because then it's the least ongoing maintenance, boots up the quickest, requires the least extra ceremony, etc.

The main issue here is my stubbornness in keeping the static builds around. I still find them useful, though. Also tricksy enough that I keep running into weird bugs that are annoying to diagnose but invariably lead to me learning something new and interesting :)

So anyway the point is, the main environmental pain-point is because I'm replicating the main Phosh build process over here in Github... but I have `phosh/` subtree vendored already, so I'm going to just wrap a GHA workflow around the upstream `.gitlab-ci/debian.Dockerfile`, and run the main Phosh + phrog CI process in that.

**Comment by samcday** [comment]
Took more than a day and two dozen failed GHA builds but I finally managed to get the stupid thing to go green. The reworked build runs the build+test phase in a custom image derived from the upstream Phosh one in registry.gitlab.gnome.org. This should hopefully be more robust and future-proof when staying abreast of ongoing Phosh development
